name: potro
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.2.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.3
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^5.1.0
  intl: ^0.18.1
  get: ^4.3.8
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0+1
  firebase_storage: ^11.1.1
  firebase_analytics: ^10.2.1
  firebase_analytics_web: ^0.5.2+1
  firebase_storage_web: ^3.1.0
  flutter_facebook_auth: ^5.0.9
  image_picker: ^0.8.7+4
  shared_preferences: ^2.2.0
  video_player: ^2.7.0
  appinio_video_player: ^1.2.1
  url_launcher: ^6.1.11
  file_picker: ^5.3.1
  flutter_pdfview: ^1.3.1
  http: ^0.13.5
  path_provider: ^2.0.15
  lottie: ^2.0.0
  flutter_file_dialog: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true
  assets:
    - assets/

  
